### ISSUE TITLE
Update the action to silence `set-output` command deprecation warning

### ISSUE THREAD

**Issue by paduszyk** [fabiocaccamo/create-matrix-action#2]
Hi ✋🏻 

When integrating the action to my project I have noticed:

<img width="1532" alt="image" src="https://github.com/fabiocaccamo/create-matrix-action/assets/92403542/a3e73ce2-6679-4bf5-a8f1-d57558d018d1">

As you can see, they suggest to update soon.

ℹ️ Details [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

Maybe you should consider to do a quick update? 🤔 

Regards! 😄

**Comment by fabiocaccamo** [comment]
@paduszyk are you using the latest version?

**Comment by paduszyk** [comment]
@fabiocaccamo, In on `fabiocaccamo/create-matrix-action@v2`.

**Comment by fabiocaccamo** [comment]
Use `v3`

**Comment by paduszyk** [comment]
Sorry, I think `v3` wasn't released as I posted that issue. Anyway, thanks.

**Comment by fabiocaccamo** [comment]
@paduszyk no worries, it was released on PyPI but I forgot to add the release here on GitHub.
